### ISSUE TITLE
can you please add support to Blocknode BND

### ISSUE THREAD

**Issue by Atabani** [mikeytown2/masternode#149]
[BND](https://github.com/zoldur/Blocknode)

[Install script](https://github.com/zoldur/Blocknode/blob/master/blocknode_install.sh)

**Comment by mikeytown2** [comment]
Script has been created https://github.com/mikeytown2/masternode/blob/master/nocollateral/blocknoded.sh

I'll need a masternodes worth of coins in order to unlock it. 

Send 100000 BND to
BMd8oymkuNNAiquQCVU7u3P5kJoiv9o8Sp

Let me know when you've done so or if you don't want to and I'll close out this issue
